[build]
  command = "echo 'Static deployment'"
  publish = "."

[[redirects]]
  from = "/display"
  to = "/btc_static.html"
  status = 200

[[redirects]]
  from = "/"
  to = "/btc_static.html"
  status = 200 