services:
  - type: web
    name: btc-macd-monitor
    env: python
    plan: free
    buildCommand: "echo 'Pure Python - No dependencies needed'"
    startCommand: "python simple_test.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MONITORING_SYMBOLS
        value: btcusdt
      - key: PRIMARY_PERIOD
        value: "15"
      - key: CHECK_INTERVAL
        value: "60"
      - key: PLATFORM
        value: render
      - key: MACD_FAST
        value: "12"
      - key: MACD_SLOW
        value: "26"
      - key: MACD_SIGNAL
        value: "9"
      - key: RSI_PERIOD
        value: "14"
      - key: RSI_OVERBOUGHT
        value: "80"
      - key: RSI_OVERSOLD
        value: "20"
      - key: COOLDOWN_PERIOD
        value: "300"
      - key: MAX_ALERTS_PER_HOUR
        value: "10" 